export {default as Login} from './Authentication/Login/Login';
export {default as Register} from './Authentication/Register/Register';
export {default as Home} from './Home/Home';
export {default as Splash} from './Splash/Splash';
export {default as CounterDown} from './Counter/CounterDown';

// Under Dashboard ( Logged In User )
export {default as VerificationCode} from './Authentication/VerificationCode/VerificationCode';
export {default as Transactions} from './DashboardContainer/Transactions/Transactions';
export {default as Dashboard} from './DashboardContainer/Dashboard/Dashboard';
export {default as Account} from './DashboardContainer/Account/Account';
export {default as Files} from './DashboardContainer/Files/Files';
export {default as FilesHeader} from './DashboardContainer/Files/FilesHeader/FilesHeader';
export {default as DashboardContainer} from './DashboardContainer/DashboardContainer';
export {default as DashboardHeader} from './DashboardContainer/Dashboard/DashboardHeader/DashboardHeader';
export {default as Uploads} from './DashboardContainer/Files/Uploads/Uploads';
export {default as ClearData} from './DashboardContainer/Dashboard/ClearData/ClearData';
export {default as UpdateProfile} from './DashboardContainer/Account/UpdateProfile/UpdateProfile';
export {default as UpdatePassword} from './DashboardContainer/Account/UpdatePassword/UpdatePassword';
export {default as InviteFriends} from './DashboardContainer/Account/InviteFriends/InviteFriends';
export {default as Images} from './DashboardContainer/Files/Uploads/Images/Images';
export {default as RegistredDevives} from './DashboardContainer/Account/RegistredDevices/RegistredDevices';
export {default as Videos} from './DashboardContainer/Files/Uploads/Videos/Videos';
export {default as Audio} from './DashboardContainer/Files/Uploads/Audio/Audio';
export {default as Documents} from './DashboardContainer/Files/Uploads/Documents/Documents';
export {default as Downloads} from './DashboardContainer/Files/Uploads/Downloads/Downloads';
export {default as Apks} from './DashboardContainer/Files/Uploads/APK/ApkFiles';
export {default as LayoutWrapper} from './DashboardContainer/Files/Uploads/LayoutWrapper/LayoutWrapper';
export {default as SellSpace} from './DashboardContainer/Dashboard/SellSpace/SellSpace'
export {default as BuySpace} from './DashboardContainer/Dashboard/BuySpace/BuySpace'
export {default as Offer} from './DashboardContainer/Dashboard/Offer/Offer'
export {default as Payments} from './DashboardContainer/Payments/Payments'